/**
 * next-intl TypeScript augmentation.
 *
 * Augments `AppConfig` from `use-intl` (re-exported via `next-intl`) with the
 * message types derived from `messages/es.json` (the canonical locale). This
 * enables compile-time type checking for all `t()` calls — calling
 * `t('missing.key')` will produce a TypeScript error if the key is absent from
 * the Spanish base messages file.
 *
 * `use-intl` is not a direct dependency of this package; it is an internal
 * dependency of `next-intl`. TypeScript module augmentation requires the module
 * to be resolvable. We declare the messages against `next-intl` instead, which
 * re-exports the same `AppConfig` interface via `use-intl/core`.
 *
 * The `messages/es.d.json.ts` declaration file is auto-generated by the
 * `createNextIntlPlugin({ experimental: { createMessagesDeclaration: ... } })`
 * option in `next.config.ts`. Run `next build` or `next typegen` to regenerate
 * it after changing `messages/es.json`.
 *
 * See: docs/research/2026-04-26-foundation.md §R4
 * See: https://next-intl.dev/docs/workflows/typescript
 */

import type messages from './messages/es.json';

// next-intl re-exports AppConfig from use-intl/core. Since use-intl is an
// internal (non-hoisted) dependency of next-intl, we augment via next-intl.
declare module 'next-intl' {
   
  interface AppConfig {
    Messages: typeof messages;
  }
}
