// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  home: {
    hero: {
      title: 'Bienvenido a Massage Tulum';
      subtitle: 'Gestión profesional para tu estudio de masajes.';
      cta: 'Comenzar';
    };
  };
  layout: {
    skipLink: 'Ir al contenido principal';
    header: {
      logoAlt: 'Massage Tulum';
    };
    footer: {
      copyright: '© {year} Massage Tulum. Todos los derechos reservados.';
    };
  };
  languageSwitcher: {
    label: 'Seleccionar idioma';
    es: 'ES';
    en: 'EN';
    esTitle: 'Español';
    enTitle: 'Inglés';
    current: 'Idioma actual: {locale}';
  };
  common: {
    loading: {
      generic: 'Cargando...';
    };
    button: {
      loading: 'Cargando...';
      retry: 'Reintentar';
      cancel: 'Cancelar';
      save: 'Guardar';
      delete: 'Eliminar';
      confirm: 'Confirmar';
      close: 'Cerrar';
    };
    error: {
      title: 'Algo salió mal';
      body: 'Por favor recarga la página.';
      reload: 'Recargar';
    };
  };
  toast: {
    dismiss: 'Cerrar notificación';
    region: {
      label: 'Notificaciones';
    };
    success: {
      loginLink: {
        title: 'Enlace enviado';
        description: 'Revisa tu correo para iniciar sesión.';
      };
      saved: {
        title: 'Cambios guardados';
        description: 'Tus cambios se guardaron correctamente.';
      };
    };
    error: {
      generic: {
        title: 'Ocurrió un error';
        description: 'Por favor intenta de nuevo. Si el problema persiste, recarga la página.';
      };
      network: {
        title: 'Sin conexión';
        description: 'Verifica tu conexión a internet e intenta de nuevo.';
      };
    };
    info: {
      generic: {
        title: 'Información';
      };
    };
  };
  auth: {
    login: {
      title: 'Accede a tu estudio';
      subtitle: 'Te enviaremos un enlace mágico a tu correo.';
      emailLabel: 'Correo electrónico';
      emailPlaceholder: 'ejemplo@tuestudio.com';
      submitButton: 'Enviar enlace de acceso';
      submittingButton: 'Enviando...';
      firstTime: '¿Primera vez? Crea tu cuenta';
      successTitle: 'Revisa tu correo';
      successMessage: 'Te enviamos un enlace a {email}. Haz clic en él para acceder.';
      resendPrompt: '¿No recibiste el correo? Revisa tu carpeta de spam, o';
      resendButton: 'solicita otro enlace';
      errors: {
        emailRequired: 'Ingresa tu correo electrónico';
        emailInvalid: 'Ingresa un correo electrónico válido';
        tooManyRequests: 'Espera un momento antes de volver a intentarlo.';
        genericError: 'Algo salió mal. Por favor intenta de nuevo.';
        linkExpired: 'Ese enlace ha expirado. Ingresa tu correo para solicitar uno nuevo.';
        invalidLink: 'Ese enlace no es válido. Ingresa tu correo para solicitar uno nuevo.';
      };
    };
    callback: {
      redirecting: 'Iniciando sesión...';
      errors: {
        linkExpired: 'Ese enlace ha expirado.';
        invalidLink: 'Enlace no válido.';
        networkError: 'Error de red. Por favor intenta de nuevo.';
      };
    };
    logout: {
      button: 'Cerrar sesión';
      allDevices: 'Cerrar en todos los dispositivos';
      confirmTitle: 'Cerrar sesión en todos los dispositivos';
      confirmBody: 'Se cerrará tu sesión en todos los dispositivos donde estés conectado. ¿Continuar?';
    };
    dashboard: {
      greeting: 'Bienvenido, {name}';
      stub: {
        title: 'Panel completo próximamente';
        body: 'Estamos preparando las herramientas de gestión para tu estudio. Vuelve pronto.';
      };
      pendingApproval: {
        title: 'Tu estudio está en revisión';
        body: 'Estamos revisando tu solicitud. Te enviaremos un correo cuando tu estudio sea aprobado.';
      };
    };
  };
  userMenu: {
    trigger: {
      label: 'Menú de usuario';
    };
    signedInAs: 'Conectado como';
  };
};
export default messages;
