// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  home: {
    hero: {
      title: 'Bienvenido a Massage Tulum';
      subtitle: 'Gestión profesional para tu estudio de masajes.';
      cta: 'Comenzar';
    };
  };
  layout: {
    skipLink: 'Ir al contenido principal';
    header: {
      logoAlt: 'Massage Tulum';
    };
    footer: {
      copyright: '© {year} Massage Tulum. Todos los derechos reservados.';
      privacyLink: 'Aviso de Privacidad';
    };
  };
  languageSwitcher: {
    label: 'Seleccionar idioma';
    es: 'ES';
    en: 'EN';
    esTitle: 'Español';
    enTitle: 'Inglés';
    current: 'Idioma actual: {locale}';
  };
  common: {
    loading: {
      generic: 'Cargando...';
    };
    button: {
      loading: 'Cargando...';
      retry: 'Reintentar';
      cancel: 'Cancelar';
      save: 'Guardar';
      delete: 'Eliminar';
      confirm: 'Confirmar';
      close: 'Cerrar';
    };
    error: {
      title: 'Algo salió mal';
      body: 'Por favor recarga la página.';
      reload: 'Recargar';
    };
    day: {
      monday: 'Lunes';
      tuesday: 'Martes';
      wednesday: 'Miércoles';
      thursday: 'Jueves';
      friday: 'Viernes';
      saturday: 'Sábado';
      sunday: 'Domingo';
      mon: 'Lun';
      tue: 'Mar';
      wed: 'Mié';
      thu: 'Jue';
      fri: 'Vie';
      sat: 'Sáb';
      sun: 'Dom';
    };
  };
  toast: {
    dismiss: 'Cerrar notificación';
    region: {
      label: 'Notificaciones';
    };
    success: {
      loginLink: {
        title: 'Enlace enviado';
        description: 'Revisa tu correo para iniciar sesión.';
      };
      saved: {
        title: 'Cambios guardados';
        description: 'Tus cambios se guardaron correctamente.';
      };
    };
    error: {
      generic: {
        title: 'Ocurrió un error';
        description: 'Por favor intenta de nuevo. Si el problema persiste, recarga la página.';
      };
      network: {
        title: 'Sin conexión';
        description: 'Verifica tu conexión a internet e intenta de nuevo.';
      };
    };
    info: {
      generic: {
        title: 'Información';
      };
    };
  };
  auth: {
    login: {
      title: 'Accede a tu estudio';
      subtitle: 'Te enviaremos un enlace mágico a tu correo.';
      emailLabel: 'Correo electrónico';
      emailPlaceholder: 'ejemplo@tuestudio.com';
      submitButton: 'Enviar enlace de acceso';
      submittingButton: 'Enviando...';
      firstTime: '¿Primera vez? Crea tu cuenta';
      successTitle: 'Revisa tu correo';
      successMessage: 'Te enviamos un enlace a {email}. Haz clic en él para acceder.';
      resendPrompt: '¿No recibiste el correo? Revisa tu carpeta de spam, o';
      resendButton: 'solicita otro enlace';
      errors: {
        emailRequired: 'Ingresa tu correo electrónico';
        emailInvalid: 'Ingresa un correo electrónico válido';
        tooManyRequests: 'Espera un momento antes de volver a intentarlo.';
        genericError: 'Algo salió mal. Por favor intenta de nuevo.';
        linkExpired: 'Ese enlace ha expirado. Ingresa tu correo para solicitar uno nuevo.';
        invalidLink: 'Ese enlace no es válido. Ingresa tu correo para solicitar uno nuevo.';
      };
    };
    callback: {
      redirecting: 'Iniciando sesión...';
      errors: {
        linkExpired: 'Ese enlace ha expirado.';
        invalidLink: 'Enlace no válido.';
        networkError: 'Error de red. Por favor intenta de nuevo.';
      };
    };
    logout: {
      button: 'Cerrar sesión';
      allDevices: 'Cerrar en todos los dispositivos';
      confirmTitle: 'Cerrar sesión en todos los dispositivos';
      confirmBody: 'Se cerrará tu sesión en todos los dispositivos donde estés conectado. ¿Continuar?';
    };
    dashboard: {
      greeting: 'Bienvenido, {name}';
      stub: {
        title: 'Panel completo próximamente';
        body: 'Estamos preparando las herramientas de gestión para tu estudio. Vuelve pronto.';
      };
      pendingApproval: {
        title: 'Tu estudio está en revisión';
        body: 'Estamos revisando tu solicitud. Te enviaremos un correo cuando tu estudio sea aprobado.';
      };
      nav: {
        studioProfile: 'Perfil del estudio';
      };
    };
    signup: {
      title: 'Registra tu estudio';
      subtitle: 'Cuéntanos sobre tu estudio y te contactaremos cuando sea aprobado.';
      fields: {
        email: 'Correo electrónico';
        emailPlaceholder: 'ejemplo@tuestudio.com';
        studioName: 'Nombre del estudio';
        studioNamePlaceholder: 'Ej. Tulum Healing Studio';
        contactPhone: 'Teléfono de contacto';
        contactPhonePlaceholder: '+52 984 000 0000';
        contactPhoneOptional: 'Opcional';
        description: 'Cuéntanos sobre tu estudio';
        descriptionPlaceholder: 'Servicios que ofreces, número de terapeutas, horarios, etc.';
      };
      submitButton: 'Enviar solicitud';
      submittingButton: 'Enviando...';
      alreadyHaveAccount: '¿Ya tienes cuenta? Accede aquí';
      successTitle: 'Solicitud recibida';
      successMessage: 'Revisaremos tu solicitud y te enviaremos un correo cuando tu estudio sea aprobado.';
      charCount: '{current}/{max}';
      privacyDisclosure: 'Al enviar este formulario, aceptas nuestro <privacyLink>Aviso de Privacidad</privacyLink>. Tus datos serán usados para crear y administrar tu cuenta de estudio en Massage Tulum. Para ejercer tus derechos ARCO, escríbenos a <arcoEmail>privacy@massage-tulum.dirk-jan.com</arcoEmail>.';
      privacyLink: 'Aviso de Privacidad';
      errors: {
        emailRequired: 'Ingresa tu correo electrónico';
        emailInvalid: 'Ingresa un correo electrónico válido';
        studioNameRequired: 'Ingresa el nombre de tu estudio';
        studioNameTooLong: 'El nombre no puede tener más de 100 caracteres';
        descriptionRequired: 'Cuéntanos sobre tu estudio';
        descriptionTooLong: 'La descripción no puede tener más de 1000 caracteres';
        genericError: 'Algo salió mal. Por favor intenta de nuevo.';
      };
    };
  };
  userMenu: {
    trigger: {
      label: 'Menú de usuario';
    };
    signedInAs: 'Conectado como';
  };
  admin: {
    pendingStudios: {
      title: 'Solicitudes pendientes';
      count: '{count, plural, one {# solicitud} other {# solicitudes}}';
      empty: 'No hay solicitudes pendientes.';
      loading: 'Cargando solicitudes...';
      columns: {
        submittedAt: 'Fecha';
        email: 'Correo';
        studioName: 'Estudio';
        contactPhone: 'Teléfono';
        description: 'Descripción';
        actions: 'Acciones';
        noPhone: 'Sin teléfono';
      };
      actions: {
        approve: 'Aprobar';
        reject: 'Rechazar';
        approveLabel: 'Aprobar: {studioName}';
        rejectLabel: 'Rechazar: {studioName}';
        approvingLabel: 'Aprobando...';
      };
      description: {
        showMore: 'Ver más';
        showLess: 'Ver menos';
      };
      approveModal: {
        title: 'Aprobar estudio';
        body: '¿Confirmas la aprobación de "{studioName}"? Se creará su cuenta y se enviará un correo de bienvenida con un enlace de acceso.';
        confirmButton: 'Aprobar';
        cancelButton: 'Cancelar';
      };
      rejectModal: {
        title: 'Rechazar solicitud';
        reasonLabel: 'Razón (opcional)';
        reasonPlaceholder: 'Ingresa un motivo para tu registro interno...';
        confirmButton: 'Rechazar';
        cancelButton: 'Cancelar';
      };
      toast: {
        approveSuccess: 'Estudio aprobado. Correo de bienvenida enviado.';
        approveError: 'No se pudo aprobar el estudio. Intenta de nuevo.';
        rejectSuccess: 'Solicitud rechazada.';
        rejectError: 'No se pudo rechazar la solicitud. Intenta de nuevo.';
        closeNotification: 'Cerrar notificación';
      };
    };
  };
  privacy: {
    meta: {
      title: 'Aviso de Privacidad — Massage Tulum';
      description: 'Conoce cómo Massage Tulum trata tus datos personales, tus derechos ARCO y cómo contactarnos.';
    };
    page: {
      title: 'Aviso de Privacidad';
      lastUpdated: 'Última actualización: {date}';
    };
    toc: {
      label: 'Contenido';
    };
    section: {
      controller: {
        heading: '1. Responsable del Tratamiento';
        body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
      };
      dataCategories: {
        heading: '2. Datos Personales que Tratamos';
        studioOwner: {
          heading: '2.1 Datos de titulares del estudio';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
        therapist: {
          heading: '2.2 Datos de terapeutas';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
      };
      purposes: {
        heading: '3. Finalidades del Tratamiento';
        primary: {
          heading: '3.1 Finalidades primarias';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
        secondary: {
          heading: '3.2 Finalidades secundarias';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
      };
      lawfulBasis: {
        heading: '4. Base Legal';
        body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
      };
      retention: {
        heading: '5. Conservación de Datos';
        body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
      };
      transfers: {
        heading: '6. Transferencias y Alojamiento de Datos';
        body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
      };
      arco: {
        heading: '7. Derechos ARCO';
        access: {
          heading: '7.1 Acceso';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
        rectification: {
          heading: '7.2 Rectificación';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
        cancellation: {
          heading: '7.3 Cancelación';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
        opposition: {
          heading: '7.4 Oposición';
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
        contact: {
          body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
        };
      };
      cookies: {
        heading: '8. Uso de Cookies';
        body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
      };
      changes: {
        heading: '9. Cambios a este Aviso';
        body: '[BLOCKING — final wording requires Mexican DPA lawyer review per OQ-6 deferral]';
      };
      effectiveDate: {
        label: '10. Fecha de Vigencia';
        value: '21 de marzo de 2025';
      };
    };
  };
  studioProfile: {
    page: {
      title: 'Perfil del estudio';
      subtitle: 'Información visible en tu página pública';
    };
    action: {
      save: 'Guardar cambios';
      cancel: 'Cancelar';
    };
    section: {
      basicInfo: 'Información general';
      contact: 'Contacto';
      hours: 'Horario de atención';
    };
    field: {
      name: {
        label: 'Nombre del estudio';
        error: {
          required: 'El nombre del estudio es obligatorio';
        };
      };
      description: {
        label: 'Descripción';
        charCount: '{count}/500';
      };
      phone: {
        label: 'Teléfono (también WhatsApp)';
        placeholder: '+52 984 123 4567';
        helper: 'Este número se usará también para mensajes de WhatsApp';
      };
      email: {
        label: 'Correo electrónico';
        error: {
          format: 'Ingresa un correo válido';
        };
      };
      contact: {
        error: {
          atLeastOne: 'Debes ingresar al menos un método de contacto (teléfono o correo)';
        };
      };
    };
    hours: {
      timezone: {
        note: 'Los horarios son en hora de Cancún (CST/CDT)';
      };
      open: 'Apertura';
      close: 'Cierre';
      closed: 'Cerrado';
      closedLabel: 'Cerrado';
      toggleClosed: {
        label: 'Marcar {day} como cerrado';
      };
      toggleOpen: {
        label: 'Marcar {day} como abierto';
      };
      error: {
        closeAfterOpen: 'La hora de cierre debe ser posterior a la de apertura';
      };
    };
    loading: 'Cargando perfil del estudio';
    empty: {
      title: 'Completa tu perfil';
      body: 'Agrega el nombre y al menos un método de contacto para comenzar';
    };
    loadError: {
      title: 'No se pudo cargar el perfil';
      body: 'Ocurrió un error al cargar los datos del estudio.';
      retry: 'Reintentar';
    };
    permission: {
      title: 'Sin acceso';
      body: 'No tienes permiso para ver esta página.';
    };
  };
};
export default messages;
